name: Build and run tests
on: [push]
jobs:
  test:
    name: Test paddle ${{ matrix.paddle_v }}
    runs-on: windows-2019
    strategy:
      matrix:
        paddle_v: [2.1.0, 2.1.3, 2.2.1]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install torch
        run: python -m pip install torch==1.9.0+cpu torchvision==0.10.0+cpu torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
      - name: Install torch-spline-conv
        run: python -m pip install torch-spline-conv -f https://data.pyg.org/whl/torch-1.9.0+cpu.html
      - name: Install paddle ${{ matrix.paddle_v }}
        run: python -m pip install paddlepaddle==${{ matrix.paddle_v }} -i https://mirror.baidu.com/pypi/simple
      - name: Run tests
        run: python test.py
